### PR TITLE
Cancel on Ctrl-G

### PR DESCRIPTION
**Pull request by hupfdule**
- `Ctrl-G` is a common key to abort some operation
- `Ctrl-G` is also used by readline to abort reverse search

### CODE REVIEW

**Comment by jbonjean** [comment]
I think this is a good idea, could you just fix the indentation (tab instead of space)?

**Comment by hupfdule** [comment]
Yes, I will do (sorry, didn't notice the tabs). 

Do you mind if I merge that change into the existing commit and force-push it to have a cleaner commit history?

**Comment by hupfdule** [comment]
Did so.

**Comment by jbonjean** [comment]
Thank you!

**Pull request merged**
