### PR TITLE
Show no of current/max history entry in prompt

### PR DESCRIPTION
**Pull request by hupfdule**
The promt is extended to display the number of the current and the
maximum history entry.

This PR depends on #21.

### CODE REVIEW

**Comment by jbonjean** [comment]
Sorry but I don't think this should be included in the default prompt, I think it's going to be too much information displayed.
We could make it optional with a compilation directive though.

**Comment by hupfdule** [comment]
OK, what's your proposal for the compilation directive?

**Comment by jbonjean** [comment]
I was thinking of a simple `#ifdef PROMPT_HISTORY_COUNT` or whatever name makes sense to you.

**Comment by hupfdule** [comment]
I'd like to postpone this. As some changes in PR #21 change the parameters of the PROMPT macro I'd like to wait after a decision was made on whether to merge PR #21.

**Comment by hupfdule** [comment]
I am closing this as #21 is also closed now.

**Pull request closed without merging**
